# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'
   
steps:
 
- script: dotnet build 'AllTheSugarFunc/AllTheSugarFunc.sln' --configuration $(buildConfiguration)
  displayName: 'Build solution'
     
- script: dotnet test 'AllTheSugarFunc/AllTheSugarFunc.Tests' --configuration $(buildConfiguration) --logger trx
  displayName: 'Run unit tests'
 
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
 
- script: dotnet publish 'AllTheSugarFunc/AllTheSugarFunc/AllTheSugarFunc.csproj' --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)/app'
  displayName: 'Package function app'
 
- task: PublishBuildArtifacts@1
  displayName: 'Publishing app artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    artifactName: app
 
- task: CopyFiles@2
  displayName: 'Copy end to end tests'
  inputs:
    sourceFolder: 'AllTheSugarFunc'
    targetFolder: '$(Build.ArtifactStagingDirectory)/e2etests'
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish end to end test artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/e2etests'
    artifactName: e2etests
